{
    "name": "Manufacturing Flow Integration",
    "version": "17.0.1.0.0",
    "summary": "Auto MO from Sale, Auto vendor selection on PO, Invoice after MO, Delivery Challan, Integration Wizard",
    "category": "Manufacturing",
    "author": "Generated by ChatGPT",
    "depends": ["sale_management","all_reports_full","dw_engineering_team","dw_stock_requisition","mrp", "purchase", "account", "stock"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "views/integration_wizard_view.xml",
        "reports/delivery_challan_report.xml",
        # "views/mrp_production.xml",
        "views/production_request_view.xml",
        "views/sale_order_view.xml",
        'views/wizard.xml',
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3"
}
