{
    'name': 'All Reports Center - Full',
    'version': '17.0.1.0.0',
    'category': 'Reporting',
    'license': 'LGPL-3',
    'depends': ['base', 'account', 'sale', 'purchase', 'stock', 'product', 'l10n_in_ewaybill_stock'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/menu_views.xml',
        'views/report_center_views.xml',
        'views/template.xml',
        'views/opening_closing.xml',
        'views/advance_vendor.xml',
        'views/vendor_ledger.xml',
        'views/customer_ledger.xml',
        'views/collection_register.xml',
        'views/outstanding_credit.xml',
        'views/payroll.xml',
        'views/material_consumption_report.xml',
        'views/bank_reconciliation_report.xml',
        'views/invoice_status.xml',
        'views/charts_of_accounts.xml',
        'views/gr_ir.xml',
        'views/customer_aging.xml',
        'views/vendor_aging.xml',
        'views/general_ledger.xml',
        'views/trial_balance.xml',
        'views/inventory_valuation.xml',
        'views/stock_register.xml',
        'views/valuation_report.xml',
        'views/journal_register_report.xml',
        'views/extended_fields.xml',
        'views/delivery_challan_report.xml',
        'views/credit_note_report.xml',
        'views/report_debit_note.xml',
        'views/purchase_order_view.xml',
        'views/quotation_report_action.xml',
        'views/purchase_order_report.xml',
        'views/quotation_report.xml',
        # 'views/product_dropdown_control.xml',
        # 'views/report_layout.xml',
    ],
    'installable': True,
    'application': True,
}
